# Generated by Django 4.2 on 2023-04-18 09:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(
                max_length=250,
                validators=[django.core.validators.MinLengthValidator(limit_value=5)],
            ),
        ),
    ]
